### ISSUE TITLE
This package could not be found

### ISSUE THREAD

**Issue by ZhaoBaymax** [NeurAI-Lab/MMC#4] opened 2022-03-11 01:58 UTC
https://github.com/NeurAI-Lab/MMC/blob/0b00b05d23c7c3400e949731f66271d72d8debf7/od/data/datasets/evaluation/coco/__init__.py#L7

hello，
I was recently doing research on infrared image recognition, and I was very interested in this project and helped me a lot. But when I was running the code, the package couldn't be found.

**Comment by shruum** [comment] 2022-06-19 20:21
Thanks for your response.
The issue is fixed in the latest commit.

**Closed as completed by shruum** 2022-06-19 20:21 UTC
